language: python 
python:
  - "3.6"
  - "3.7"
  - "3.8"
services:
  - postgresql
env: 
  - DJANGO=1.4.1
install:
  - pip install -r requirements.txt
script: 
  - cd django-pg-upsert/tests
  - python test_upsert.py
