language: python # => 1
    python: # => 2
      - "2.6"
      - "2.7"
    services: # => 3
      - mysql
    env: # => 4
      -DJANGO=1.8 DB=mysql
    install: # => 5
      - pip install -r requirements.txt
    before_script: # => 6
      - mysql -e 'create database test;' -u root
    script: # => 7
      - python manage.py test
